//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MusicPlayer;

public interface Player extends com.zeroc.Ice.Object
{
    int GetNumberOfMusics(com.zeroc.Ice.Current current);

    void AddMusic(int offset, byte[] partiesMusique, String path, com.zeroc.Ice.Current current);

    void AddMusicDatabase(String titre, String artistes, String album, int duree, com.zeroc.Ice.Current current);

    void DeleteMusic(String name, com.zeroc.Ice.Current current);

    void ModifyMusic(String musiqueAModifier, String nouveauTitre, String nouveauxArtistes, String nouvelAlbum, com.zeroc.Ice.Current current);

    String[] PrintMusics(int i, com.zeroc.Ice.Current current);

    boolean Play(String music, com.zeroc.Ice.Current current);

    String Pause(com.zeroc.Ice.Current current);

    boolean Stop(com.zeroc.Ice.Current current);

    void SearchTitle(String title, com.zeroc.Ice.Current current);

    void searchArtist(String artist, com.zeroc.Ice.Current current);

    void Avancer(int secondes, com.zeroc.Ice.Current current);

    void Reculer(int secondes, com.zeroc.Ice.Current current);

    String[] AsrNlp(com.zeroc.Ice.Current current);

    void send(int offset, byte[] chunk, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::MusicPlayer::Player"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::MusicPlayer::Player";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_GetNumberOfMusics(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        int ret = obj.GetNumberOfMusics(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeInt(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_AddMusic(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_offset;
        byte[] iceP_partiesMusique;
        String iceP_path;
        iceP_offset = istr.readInt();
        iceP_partiesMusique = istr.readByteSeq();
        iceP_path = istr.readString();
        inS.endReadParams();
        obj.AddMusic(iceP_offset, iceP_partiesMusique, iceP_path, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_AddMusicDatabase(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_titre;
        String iceP_artistes;
        String iceP_album;
        int iceP_duree;
        iceP_titre = istr.readString();
        iceP_artistes = istr.readString();
        iceP_album = istr.readString();
        iceP_duree = istr.readInt();
        inS.endReadParams();
        obj.AddMusicDatabase(iceP_titre, iceP_artistes, iceP_album, iceP_duree, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_DeleteMusic(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_name;
        iceP_name = istr.readString();
        inS.endReadParams();
        obj.DeleteMusic(iceP_name, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_ModifyMusic(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_musiqueAModifier;
        String iceP_nouveauTitre;
        String iceP_nouveauxArtistes;
        String iceP_nouvelAlbum;
        iceP_musiqueAModifier = istr.readString();
        iceP_nouveauTitre = istr.readString();
        iceP_nouveauxArtistes = istr.readString();
        iceP_nouvelAlbum = istr.readString();
        inS.endReadParams();
        obj.ModifyMusic(iceP_musiqueAModifier, iceP_nouveauTitre, iceP_nouveauxArtistes, iceP_nouvelAlbum, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_PrintMusics(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_i;
        iceP_i = istr.readInt();
        inS.endReadParams();
        String[] ret = obj.PrintMusics(iceP_i, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_Play(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_music;
        iceP_music = istr.readString();
        inS.endReadParams();
        boolean ret = obj.Play(iceP_music, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_Pause(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String ret = obj.Pause(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_Stop(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        boolean ret = obj.Stop(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeBool(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_SearchTitle(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_title;
        iceP_title = istr.readString();
        inS.endReadParams();
        obj.SearchTitle(iceP_title, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_searchArtist(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_artist;
        iceP_artist = istr.readString();
        inS.endReadParams();
        obj.searchArtist(iceP_artist, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_Avancer(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_secondes;
        iceP_secondes = istr.readInt();
        inS.endReadParams();
        obj.Avancer(iceP_secondes, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_Reculer(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_secondes;
        iceP_secondes = istr.readInt();
        inS.endReadParams();
        obj.Reculer(iceP_secondes, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_AsrNlp(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String[] ret = obj.AsrNlp(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_send(Player obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_offset;
        byte[] iceP_chunk;
        iceP_offset = istr.readInt();
        iceP_chunk = istr.readByteSeq();
        inS.endReadParams();
        obj.send(iceP_offset, iceP_chunk, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "AddMusic",
        "AddMusicDatabase",
        "AsrNlp",
        "Avancer",
        "DeleteMusic",
        "GetNumberOfMusics",
        "ModifyMusic",
        "Pause",
        "Play",
        "PrintMusics",
        "Reculer",
        "SearchTitle",
        "Stop",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "searchArtist",
        "send"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_AddMusic(this, in, current);
            }
            case 1:
            {
                return _iceD_AddMusicDatabase(this, in, current);
            }
            case 2:
            {
                return _iceD_AsrNlp(this, in, current);
            }
            case 3:
            {
                return _iceD_Avancer(this, in, current);
            }
            case 4:
            {
                return _iceD_DeleteMusic(this, in, current);
            }
            case 5:
            {
                return _iceD_GetNumberOfMusics(this, in, current);
            }
            case 6:
            {
                return _iceD_ModifyMusic(this, in, current);
            }
            case 7:
            {
                return _iceD_Pause(this, in, current);
            }
            case 8:
            {
                return _iceD_Play(this, in, current);
            }
            case 9:
            {
                return _iceD_PrintMusics(this, in, current);
            }
            case 10:
            {
                return _iceD_Reculer(this, in, current);
            }
            case 11:
            {
                return _iceD_SearchTitle(this, in, current);
            }
            case 12:
            {
                return _iceD_Stop(this, in, current);
            }
            case 13:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 14:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 15:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 16:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 17:
            {
                return _iceD_searchArtist(this, in, current);
            }
            case 18:
            {
                return _iceD_send(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
